# docker-compose.yml
version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - session-service
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: grafana
    volumes:
      - ./config/grafana-ds.yml:/etc/grafana/provisioning/datasources/default-datasource.yaml
      - ./config/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/default-dashboard.yaml
      - ./config/session-dashboard.json:/etc/grafana/provisioning/dashboards/session-dashboard.json
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
  speaker-service:
    container_name: speaker
    image: payara/micro:5.2020.4-jdk11
    ports:
      - "8881:8080"
    volumes:
      - ./Speaker/target/microservice-speaker.war:/opt/payara/deployments/microservice-speaker.war
    command: --noCluster --deploy /opt/payara/deployments/microservice-speaker.war --contextRoot /
  session-service:
    container_name: session
    depends_on:
      - speaker-service
    image: payara/micro:5.2020.4-jdk11
    environment:
      - fish.payara.demos.conference.session.rs.clients.SpeakerServiceClient/mp-rest/url=http://speaker:8080/
      - fish.payara.demos.conference.session.rs.clients.VenueServiceClient/mp-rest/url=http://speaker:8080/
    ports:
      - "8882:8080"
    volumes:
      - ./Session/target/microservice-session.war:/opt/payara/deployments/microservice-session.war
    command: --noCluster --deploy /opt/payara/deployments/microservice-session.war --contextRoot /