global:
  scrape_interval: 15s
  external_labels:
    monitor: 'session-monitor'
scrape_configs:
  - job_name: 'session-service'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['session:8080']