{
 "title": "Session Dashboard",
 "description": "Shows session data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Session Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Spaces",
   "type": "gauge",
   "description": "Current available spaces",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "application_session_spaces" }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "description": "Data on operation attempts",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Attempts" }
   ],
   "targets": [
    {
     "expr": "rate(application_session_creation_tries_total[1m])",
     "legendFormat": "Creation"
    },
    {
     "expr": "rate(application_session_deletion_tries_total[1m])",
     "legendFormat": "Deletion"
    }
   ]
  },
  { "title": "Duration Histograms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Minimum (seconds)",
   "type": "stat",
   "description": "Max duration",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_session_duration_history_min_seconds"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "graph",
   "description": "Distribution statistics",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Duration in Seconds" }
   ],
   "targets": [
    {
     "expr": "application_session_duration_history_mean_seconds",
     "legendFormat": "Mean"
    },
    {
     "expr": "application_session_duration_history_stddev_seconds",
     "legendFormat": "Std. Deviation"
    }
   ]
  },
  {
   "title": "Maximum(seconds)",
   "type": "stat",
   "description": "Max duration",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_session_duration_history_max_seconds"
    }
   ]
  }
 ]
}